### ISSUE TITLE
What is the kind of a hole type?

### ISSUE THREAD

**Issue by hmac** [hackworthltd/primer#108]
Our current set of kinds are `Type` and `Type → Type`. In types and expressions we have a special value `?` which represents an unknown, but we don't have an equivalent in kinds.

So what is the kind of the type `?`? If it is `Type` then we can't use holes in places where higher kinded types are expected, for example in
```
let f = λxs → map inc xs : ? Nat
 in ...
```
where `?` might be written in place of `List` when the user hasn't worked out what it should be yet.

Conversely, if its kind were `Type → Type` or `Type → Type → Type` then we'd rule out using it in place of basic types.]

We discussed this briefly in chat:

```
Harry: What kind does type `?` have? Do we need a kind `?` ?

Ben: Interesting! I think we can choose what to support here.
  In general a unknown kind sounds sane, but I don't know if it would be useful.
  We should think about the knock on effects of this choice - it's not clear to me.
  One option I think would be to disallow explicitly writing unknown types -
  i.e. "types first" means "fully known ...", then I hope we can know the kind of any type hole.
  Not sure on any of this though!

Harry: That option seems to imply that we'd take a bidirectional approach to kind checking.
  So e.g. a type constructor can synthesise a kind but a type hole can only be checked against a kind.

Ben: Perhaps. I was hoping that when we generate a type hole, we could also generate its kind.
  i.e. have one sort of type hole per kind.
  Further hoping that all type holes would have kind TYPE. But really haven't thought that bit through!

Harry: I doubt the latter holds if we let the user put holes in arbitrary places in types.
  It may hold if we ban that, though.
  I wonder what would be the UX implications of only allowing type holes of kind TYPE...
```

**Comment by brprice** [comment]
Closing as we made the choice to have kind holes (in the sense of one flavor of kind hole which is consistent with all kinds), and implemented it ages ago. I don't think there is anything else to consider here. Feel free to reopen if I am mistaken!
