### ISSUE TITLE
FR: Provide API for displaying and editing kinds on foralls

### ISSUE THREAD

**Issue by georgefst** [hackworthltd/primer#1098]
## Description

This is a feature request.

In https://github.com/hackworthltd/primer/pull/1095, we add support for editing kinds in the context of type parameters in a type definition. But there is another place where kinds can appear in a program: every ∀ node contains the kind of the type variable which it quantifies over (we also introduce type variables in Λ nodes but these do not store the kind - I'm not personally totally sure why, but I guess we just don't need to).

While #1095 achieves the goal that all _typedefs_ supported in the language can now be constructed via the OpenAPI, this proposal would allow us to construct all supported _programs_.

## Dependencies

#1095

## Spec

Similarly to #1095, we should output these kinds in trees, and provide actions (core and "available" actions) for manipulating them.

## Implementation details

I see this as essentially "kind edits stage 2", with https://github.com/hackworthltd/primer/pull/1095 being "stage 1". A few things in that PR (particularly the main "Implement actions" commit f5c7a18) are implemented in a slightly ad-hoc way pending the implementation of additional machinery, which I propose to add as part of this feature. In particular, the `Loc` type will need to be extended to cover kinds as well as expressions and types. See:

- https://github.com/hackworthltd/primer/pull/1095#discussion_r1275520797
- https://github.com/hackworthltd/primer/pull/1095#discussion_r1275523570
- https://github.com/hackworthltd/primer/pull/1095#discussion_r1275524020

Additionally, we still have `TForall a TyVarName (Kind' ()) (Type' a)`, i.e. the attached kind does not even have metadata. So this first step is to add metadata here, in place of `()`. This will require a lot of extra type parameters to be plumbed around, as we move from `Expr' a b`/`Expr' ExprMeta TypeMeta` to `Expr' a b c`/`Expr' ExprMeta TypeMeta KindMeta`, and similarly `Type' b` to `Type' b c`. There will be a lot of churn in tests especially, replacing every `tforall _ (KType ())` and similar. But, beyond being laborious to refactor, I don't _think_ any of this this is a major concern, in the way it might be if we made a lot of use of `Bifunctor`/`Bitraversable` etc. for `Expr`.

## Future work

There is a discussion to be had about simplifying kind-related functionality in beginner/intermediate mode, e.g. by trimming kinds from the tree entirely. But let's leave this for now. Displaying different trees at different levels would be a big step up from the level-dependent behaviour we currently have, and would bring some challenges, such as what to do when a program containing higher kinds is opened in beginner mode. This is all more relevant to #1095 anyway, since foralls cannot be constructed in beginner mode.

This would be an opportune time to add IDs to patterns. Then all nodes in the program would have numeric identifiers (and a corresponding `Selection`), simplifying communication with clients. Where by "nodes" we mean stuff which appears in actual arbitrarily-nestable trees, as opposed to other more static things which our frontend may render similarly to nodes, such as definition names or constructors and parameters in a typedef (all of which have a `Selection` which doesn't contain an `ID`).

**Comment by brprice** [comment]
One simple thought/todo that occurred when reviewing #1095 : when we implement this fr, we should ensure to update the `_typeMeta` and(?) `_exprMeta` traversals, which target every meta. E.g. `_exprMeta` recurses inside type annotations etc, so for consistency `_typeMeta` should go inside kinds on foralls.
