### ISSUE TITLE
Rename `fold(r)` to `crush(r)`

### ISSUE THREAD

**Issue by dhess** [hackworthltd/primer#1103]
See relevant discussion here:

https://types.pl/@pigworker/110830915576334327

**Comment by georgefst** [comment]
It sounds like Conor is suggesting "crush" for "the monoidal crushing of the payload of a container", which is not Primer's/Haskell's `foldr` etc. but Haskell's `fold :: Monoid m => t m -> m ` (a generalisation of `mconcat`, in further unfortunate naming), which we don't have in Primer, and doesn't make much sense without typeclasses.
