### ISSUE TITLE
chore: remove workaround for ghc 9.6.2 spurious warning when we upgrade to ghc 9.6.3

### ISSUE THREAD

**Issue by brprice** [hackworthltd/primer#1152]
In #1113 we bumped to ghc 9.6.2 but discovered there was a bug with spurious warnings and `deriving`: https://gitlab.haskell.org/ghc/ghc/-/issues/23143. We added some pragmas `{-# OPTIONS -Wno-redundant-constraints #-}` (e.g. https://github.com/hackworthltd/primer/blob/091330c99ac9fcfb748a64002c2a94df0e522abc/primer-api/src/Primer/API.hs#L10) to silence these. The issue is now fixed upstream, and released in ghc 9.6.3. When we upgrade ghc (note that haskell.nix does not yet support 9.6.3) we should remove these pragmas, so they do not quash other (valid) warnings. (We may also want to bump a minimum version bound to enforce ghc 9.6.3's use)

**Comment by georgefst** [comment]
> We may also want to bump a minimum version bound to enforce ghc 9.6.3's use

I'd be inclined not to. Being warning-free across versions tends to be more effort than it's worth (although it is a shame that "warnings" in GHC can be anything from totally harmless (e.g. missing signature) to essentially errors (incomplete patterns) - though this may improve soon: https://github.com/ghc-proposals/ghc-proposals/pull/571).
