### ISSUE TITLE
Wildcard patterns

### ISSUE THREAD

**Issue by dhess** [hackworthltd/primer#335]
Note that this issue is a special case of #334. We may want to support wildcard patterns (e.g., a la `_` in Haskell) as a special case before we try to implement more generally flexible pattern matching. These should be relatively easy for beginners to understand and should be quite useful.

Note that implementing this will require some sort of overlap checker.

(There are Primer frontend UI issues to consider here, as well, but we should do that on the `primer-app` repo.)

**Comment by georgefst** [comment]
> This was completed in #957.

Looks like the wrong link. https://github.com/hackworthltd/primer/pull/1049?

**Comment by dhess** [comment]
yeah, I was looking at the `primer-app` repo when I wrote that.
