### ISSUE TITLE
API should provide a way to get all constructor names in a given module

### ISSUE THREAD

**Issue by dhess** [hackworthltd/primer#830]
This feature would permit client-side validation of typedefs, which should provide slightly nicer UX.

**Comment by dhess** [comment]
We don't need this feature anymore, or at least, we don't need it for the "create-a-typedef" UI form, as constructors are now created through edit actions in the structure editor, and not in the form. I'm not aware of any other current needs or use cases, so let's close this.

**Comment by georgefst** [comment]
> This should probably be exposed just emitting the constructors in each typedef -- currently we simply list the names of the types defined in a module, but don't say what their constructors are. (This was done simply for convenience, since we had no consumers who wanted this data)

Note that we actually made this change in order to enable the new structure editing for typedefs. So this should probably have already been closed anyway.
