### ISSUE TITLE
Indicate to OpenAPI client whether undo is available

### ISSUE THREAD

**Issue by dhess** [hackworthltd/primer#921]
Now that we have undo in the OpenAPI API, it would be nice for frontends to be able to tell whether undo is available: if it's not, any undo button/UI element should be greyed out, hidden, etc.

This should probably be ambient &mdash; e.g., provided as part of the transmitted `Prog`, or some wrapper around it &mdash; rather than a separate API call.

**Comment by brprice** [comment]
This was done as part of #922
